source 'https://github.com/CocoaPods/Specs.git'

#target 'NSDate-Additions', :exclusive => true do
#  
#end

pod "NSDate-Additions", :path => "../"

target 'Tests', :exclusive => true do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
